export const ErrorCodes = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_INACTIVE: 'EMPLOYEE_INACTIVE',
  EMPLOYEE_ALREADY_EXISTS: 'EMPLOYEE_ALREADY_EXISTS',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  DEVICE_TOKEN_INVALID: 'DEVICE_TOKEN_INVALID',
  REGISTRATION_CODE_EXPIRED: 'REGISTRATION_CODE_EXPIRED',
  REGISTRATION_CODE_USED: 'REGISTRATION_CODE_USED',
  REGISTRATION_CODE_INVALID: 'REGISTRATION_CODE_INVALID',
  INVALID_EVENT_TYPE: 'INVALID_EVENT_TYPE',
  INVALID_TIMESTAMP: 'INVALID_TIMESTAMP',
  INVALID_STATUS: 'INVALID_STATUS',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  CONFLICT: 'CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
